[build]
  command = "yarn generate"
  publish = "dist"

# Specific branch context: Deploys from this branch
# will take these settings and override their current ones.

# deploy previews
# pull requests
[context.deploy-preview]
[context.deploy-preview.environment]
  NODE_ENV = "development"

# develop--
# active development
[context.develop]
[context.develop.environment]
  NODE_ENV = "development"

# production
[context.production]
[context.production.environment]
  NODE_ENV = "production"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    # Block site from being framed with X-Frame-Options and CSP
    Content-Security-Policy = '''
      default-src https:;
      script-src https: 'self' 'unsafe-inline' 'unsafe-eval';
      style-src https: 'unsafe-inline';
      object-src 'none';
      img-src https:;
      connect-src https:;
      frame-src  https:;
      frame-ancestors 'none';
    '''

    # Only connect to this site and subdomains via HTTPS for the next one year
    Strict-Transport-Security = "max-age=31536000"

    # X-Frame-Options tells the browser not to allow framing of the site. By preventing a browser from framing your site you can defend against attacks like clickjacking.
    X-Frame-Options = "DENY"

    # X-XSS-Protection sets the configuration for the cross-site scripting filter built into most browsers.
    X-XSS-Protection = "1; mode=block"

    # Prevent browsers from incorrectly detecting non-scripts as scripts
    X-Content-Type-Options = "nosniff"
